package app.web.diegoflassa_site.littledropsofrain.buildsrc

@Suppress("Unused")
object Versions {
    const val ktlint = "0.41.0"
    const val kotlinCompilerVersion = "1.4.32"
    const val gradle="7.1.0-alpha01"
    const val coil = "1.0.0"
    const val data_store = "1.0.0-alpha08"
	const val gson = "2.8.6"
    const val retrofit = "2.0.0"
    const val retrofit_adapter = "2.9.0"
    const val converter = "2.9.0"
    const val converter_jackson = "2.9.0"
    const val jackson = "2.12.3"
    const val rxjava = "3.0.13-RC2"
    const val rxandroid = "3.0.0"
    const val koin = "3.0.1"
    const val volley = "1.2.0"
    const val ucrop = "2.2.6"
    const val oss = "17.0.0"
    const val oauth2 = "0.22.1"
    const val leakcanary = "2.4"
    const val play_services_auth = "19.0.0"
    const val material = "1.3.0"
    const val play_services_location = "18.0.0"
    const val google_services = "4.3.5"
    const val activity_ktx = "1.3.0-alpha05"
    const val annotation = "1.3.0-alpha01"
    const val appcompat = "1.3.0-rc01"
    const val browser = "1.3.0"
    const val constraintlayout = "2.0.4"
    const val core_ktx = "1.3.2"
    const val fragment_ktx = "1.3.2"
    const val legacy_support_v4 = "1.0.0"
    const val legacy_support_core_utils = "1.0.0"
    const val lifecycle = "2.3.1"
    const val navigation = "2.3.4"
    const val preference_ktx = "1.1.1"
    const val recyclerview = "1.2.0"
    const val recyclerview_selection = "1.1.0"
    const val room = "2.3.0-beta02"
    const val vectordrawable_animated = "1.1.0"
    const val databinding = "4.1.1"
    const val core = "1.3.1-alpha05"
    const val espresso = "3.4.0-alpha05"
    const val test = "1.4.0-alpha05"
    const val junit_ktx = "1.1.3-alpha05"
    const val safeargs_plugin="2.3.1"
    const val crashlytics = "2.4.1"
    const val perf = "1.3.4"
	const val app_distribution = "2.0.1"
    const val oss_plugin="0.10.2"
    const val spotless="5.8.2"
    const val junit = "4.13.2"
    const val auth = "6.3.0"
	
    const val database = "4.0.0"
    const val storage = "6.2.1"
    const val workVersion = "2.7.0-alpha01"
    const val firebaseBOM = "28.0.1"
    const val iconify = "2.2.2"
    const val androidxJetpackCompose = "1.0.0-beta07"
    const val foundation = "1.0.0-alpha11"
}